

CREATE TABLE IF NOT EXISTS PUBLIC.USER(
    ID 			BIGINT NOT NULL,
    NAME 		VARCHAR(255),
    PHONENUMBER VARCHAR(255),
	EMAIL		VARCHAR(255),
	ROLE_ID		INT,
	CREATED_DATE		DATE,
	LAST_MODIFIED_DATE  DATE
);            
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
CREATE SEQUENCE PUBLIC.USER_SEQUENCE START WITH 100;
/*************/
CREATE TABLE IF NOT EXISTS PUBLIC.STOCK(
    ID 			BIGINT NOT NULL,
    NAME 		VARCHAR(255),
    CODE	 	VARCHAR(255),
	CREATED_DATE		DATE,
	LAST_MODIFIED_BY	VARCHAR(255),
	LAST_MODIFIED_DATE  DATE,
	PRICE		BIGINT
);            
ALTER TABLE PUBLIC.STOCK ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);
CREATE SEQUENCE PUBLIC.STOCK_SEQUENCE START WITH 100;


/*************/
CREATE TABLE IF NOT EXISTS PUBLIC.ROLE(
    ID 			BIGINT NOT NULL,
    NAME 		VARCHAR(255)
);            
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);
CREATE SEQUENCE PUBLIC.ROLE_SEQUENCE START WITH 100;